apiVersion: v2
name: thesaas-company
description: A Helm chart for TheSaaS Company application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: flux2
    version: 2.13.0
    repository: https://fluxcd-community.github.io/helm-charts
  - name: cert-manager
    version: v1.15.3
    repository: https://charts.jetstack.io