apiVersion: v2
name: thesaas-company
description: A Helm chart for TheSaaS Company application
type: application
version: 0.1.1
appVersion:  0.1.1
dependencies:
  - name: flux2
    version: 2.13.0
    alias: flux
    condition: flux.enabled
    repository: https://fluxcd-community.github.io/helm-charts
  - name: cert-manager
    version: v1.15.3
    alias: cert-manager
    condition: cert-manager.enabled
    repository: https://charts.jetstack.io