apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thesaas-company.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thesaas-company.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "thesaas-company.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thesaas-company.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "thesaas-company.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- if .Values.secretName }}
            - name: SAAS_COMPANY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: token
            {{- end }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port | default 80 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
