apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thesaas-company.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thesaas-company.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "thesaas-company.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thesaas-company.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "thesaas-company.fullname" . }}-sa
      containers:
        - name: {{ .Chart.Name }}
          command: ["/app/saas"]
          args: ["serve", "--id", "{{ .Values.id }}"]  # Added argument here
          env:
            - name: SAAS_COMPANY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "thesaas-company.fullname" . }}-secret
                  key: token
            - name: NAMESPACE_NAME  # Added environment variable for namespace
              value: {{ .Release.Namespace }}  # Set value to the namespace
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}

          livenessProbe:
            httpGet:
              path: /
              port: 80  # Changed port to 80 for liveness check
          readinessProbe:
            httpGet:
              path: /
              port: 80  # Changed port to 80 for readiness check
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
