name: 🚀 Release

on:
  push:
    # run only against tags
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write 
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.10.3

      - name: Install Cosign
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 # v3.1.1

      - name: Setup pybump
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          pip install pybump
          pybump set --file charts/thesaas-company/Chart.yaml --set-version ${GITHUB_REF#refs/*/}
          
      - name: Run chart-releaser
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260 #v1.7.0
        with:
          token: "${{ secrets.GH_TOKEN }}"
          linting: off
          charts_dir: charts

      - name: Login to GitHub Container Registry
        run: |
          helm registry login --username thesaas-company --password ${{ secrets.GH_TOKEN }} ghcr.io
      
      - name: Publish OCI Charts
        run: |
          for dir in `find charts -maxdepth 1 -mindepth 1 -type d -print`; do
            chart=${dir##*/}
            echo "Found chart: ${chart}"
            helm package charts/${chart} --destination .dist
            helm push .dist/${chart}-*.tgz oci://ghcr.io/thesaas-company/${chart} |& tee .digest
          done
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN }}"
